### ISSUE TITLE
Stack frame objects? Opinions welcome

### ISSUE THREAD

**Issue by maximecb** [maximecb/zeta#10]
I've been thinking it might be interesting to make [stack frames](https://en.wikipedia.org/wiki/Call_stack) in zeta accessible as first-class objects. There's some elegance to this scheme. With prototypal inheritance, stack frames from closures can inherit from the stack frame of the calling function. All stack frames inherit from the object representing the current module (zeta source file), which in turn inherits from the root global object.

This would have some advantages when it comes to live coding, as well as implementing a debugger. Might also simplify things when implementing our interpreter, and switching between the interpreter context and the JIT. It's common in VM to implement some mapping of local variables to values. This is very much an object by nature, it's just not a first-class object in most languages.

Further advantages are that it could facilitate the implementation of continuations and things such as coroutines. There's also `eval`. I've always thought that eval should take some sort of an environment object as a parameters, instead of being granted access to all local variables. With this, you can do `eval("foo", $global)` or `eval("foo", $frame)` or even `eval("foo", myCustomEnvironmentObject)`.

Obviously, the downside is performance. Allocating stack frames on the heap and garbage-collecting them can be expensive. Then we also have the issue that all local variable reads and writes become object property accesses.

I think that allocation of stack frames can be optimized fairly effectively. We can stack allocate the frames. Then, if anyone ever wants to use the stack frame as a "real" object, we copy it on the heap. This is essentially [partial allocation sinking](http://wiki.luajit.org/Allocation-Sinking-Optimization).

With respect to the overhead of property reads and writes, I think we can defer most of these. Local variable behave like object properties, but obviously we'd have a register allocator, and manipulate locals through registers as much as possible. The stack frame remains on the stack, with nothing written to it for as long as possible. 

But, of course, maybe I'm being a bit naive and this is more difficult to optimize than it looks. Maybe it's not worth having as a language feature.

**Comment by maximecb** [comment]
I guess I just realized there is an issue with temporaries and whether these should be stored in stack frame objects, etc. I'm also hoping to dynamically grow stack frames when implementing a JIT.

**Comment by maximecb** [comment]
I think the niftiest thing about "stack frames as objects" is that all variable lookups become just object property lookups, following the normal object property lookup semantics.

The main complications are that we may need to manage multiple virtual stack frame objects when doing inlining. Though I suppose, in theory, that's no more complex than just managing one stack frame.

JS objects typically have "slots" and are preallocated with some given capacity (e.g.: 10 slots). Variables are written to the slots as they are added. Temporaries can possibly be written into slots that are not yet allocated to anything so that they don't exist as named properties on the object, or given unique names such as $tmp5.

Ideally, values which are no longer live would be deleted from the object so they become inaccessible. The downside here is that stack frame objects would likely have many different shapes based on what is and isn't live. The number of shapes is probably manageable in most cases (10s to a few hundred), but there is the potential for exponential growth in some pathological cases, especially if we allow property deletions when variables are no longer live. Some mechanisms would be needed to deal with pathological cases.

So far, I think that stack frame objects offer some nifty possibilities, but the use cases aren't really clear, and they might bring more complication than they are worth. We'd have to do a really really good job of optimizing everything object related.

**Comment by edgemaster** [comment]
JS has been pushing away from mutable stack frame objects due to difficulty performing static analysis and (human) reasoning about what variables are currently in scope.
One relevant paper that addresses the security issues is "Automated Analysis of Security-Critical JavaScript APIs" by Taly et al, in 2011 IEEE Symposium on Security and Privacy. [1]
This paper also has a form of restricted eval which specifies which variables are permitted to be unbound in the evaluated code. In the actual implementation of SES [2], this is pretty much the same as your `eval("foo", myCustomEnvironmentObject)` case above.

[1] http://research.google.com/pubs/pub37199.html
[2] https://github.com/google/caja/blob/master/src/com/google/caja/ses/startSES.js#L1137

(@erights may also be interested/more knowledgable in this discussion)

**Comment by erights** [comment]
Regarding stack frames as objects, this is now almost completely irrelevant to modern JS with the coming of strict mode. ES3 had six violations of static scope. Three are fixed unconditionally by moving to ES5, the remaining three are fixed in strict mode. In ES6, modules and classes are both implicitly strict, making strict mode the dominant mode going forward. Best to consider sloppy mode as only an ES3 compatibility mode.

Regarding SES, the irony is that, for reasons related to the subject of this thread, to implement SES so it adequately emulates ES5/strict, I actually use "with" in the implementation.

**Comment by maximecb** [comment]
I guess I'm not too worried about static analysis, but it could be a poor idea to make static analysis more difficult. In any case, stack frame objects may be too tall of an order. It's probably best to implement that kind of feature when a need has been shown, as opposed to "wouldn't it be cool if we did x".

@erights: what does it change for modules to be implicitly strict? what are the semantic differences there?

**Comment by erights** [comment]
In strict mode, all violations of static scoping are gone, including "with". For every use-occurrence of a variable, you can always statically tell whether it is free in the module, and if not, what defining-occurrence it refers to.

**Comment by erights** [comment]
Regarding Zeta, I cannot offer advice regarding this or any other issue without understanding what goals you have in mind. What do you want Zeta to be especially good at? What are some major goals of other languages that Zeta does not care about or is willing to sacrifice?

**Comment by maximecb** [comment]
I'd like to target live coding in particular, but with good performance (fairly close to modern JS engine performance). Things we can sacrifice, not entirely sure. It will be JIT compiled. I intend to take advantage of my research on basic block versioning to produce fast machine code. I think we can largely give up on static compilation, the semantics of the language will make that difficult slash impossible, especially once we get into grammar extensions.

Users will be able to completely hijack the parser if they want to (but only locally, in the current module). Hence, you could load up a language extension module and suddenly be writing in a lisp-like syntax if you want to, or have something like PHP for generating web templates. That will probably be our biggest feature to begin with. I'm sure a lot of people are going to say "this is dangerous!", but the kinds of things that will be possible in terms of domain-specific languages are going to make Pythonistas and LISPers throw fits of intense jealousy.

It's also going to be possible to generate x86 machine code from zeta, and eventually extend the JIT so you can make your own language extensions fast. Hence, I guess we're giving up on "safety". Zeta will be a bit C++ like in that regard, it will let you bazooka yourself in the foot if you really want to. 

I think I'd like a foundational principle a bit like C++, that is, pay for what you use. If you write "sane" code, it will be quite safe and will give you "good" performance (close to JS or GCC -O0). We won't intentionally have people manipulating raw pointers and we won't encourage people to extend the grammar, we won't tempt them to sin, we'll provide safe abstractions and curated language extensions. But, Zeta will be a hacker's language. Something demoscene people might want to use, something *fun* to program in.

**Comment by erights** [comment]
Live coding would be the goal that would most touch on this thread's issues. What happens when code is revised while there are outstanding stack frames that only made sense for the old version of that code? How does execution proceed using the data from the old stack frames while behaving according to the new code?

This is essentially the object/schema evolution problem that also comes up with persistent object systems. Smalltalk was both live (in a sense) and persistent, and did face all these issues. It is worth studying, even if their approach is unsatisfying.

Intermediate between stack frames and objects are state captured by closures. These are as implicit as stack frames but have the longevity of objects, making them perhaps the hardest case for live programming.

**Comment by erights** [comment]
Smalltalk did reify stack frames as objects, btw.

**Comment by maximecb** [comment]
Yes, I'm aware, that's why I thought it might be wise to do as Smalltalk did. I thought perhaps reified stack frames would make live coding, debugging and other interesting things more elegant. At the same time, it is clearly opening up a pandora's box of "omg why did you write that code!".

I guess in terms of live coding, it would be interesting to be able to edit functions and have them run the new code. The least we can do is wait for functions using the old code to terminate, and have new calls go to the new code. That's probably the easiest to implement.

**Comment by erights** [comment]
Starting with Smalltalk's "solutions" to these issues would be great. For all their problems in theory, it all worked fantastically in practice. Over and over again I remember fixing code from within the debugger and then proceeding to single step execution at the immediately next outer frame.

> The least we can do is wait for functions using the old code to terminate, and have 
> new calls go to the new code.

That's why I brought up closures, because of their unlimited lifetime. Smalltalk did indeed never upgrade an already-instantiated closure, but rather had it continue execution using both its old code and its old state. Nevertheless, I never noticed this as a problem in practice.

**Comment by maximecb** [comment]
What did the reified stack frames as objects bring to Smalltalk, would you say? What were the advantages of it?

**Comment by cfbolz** [comment]
Smalltalk uses reified stack frames most importantly to implement the debugger in Smalltalk itself. Same is true for Python.

The cost of them can be very low in JITs like VisualWorks (and PyPy): As long as no code touches the reified frame, it's not filled with any content. Only if you e.g. start a debugger, is the information retrieved from the CPU stack and put into the frames. Here's a (somewhat hard to read) paper about how VisualWorks does it: http://www.esug.org/data/Articles/misc/oopsla99-contexts.pdf

**Comment by cfbolz** [comment]
(In Smalltalk you could do a lot of weird other things with reified frames, because it was possible to not only read from the frame, but also write to it, including the PC and things on the stack. Here's an example: http://portal.acm.org/citation.cfm?id=62084.62094 I highly doubt that any VM made code like that efficient.)

**Comment by maximecb** [comment]
@cfbolz If you'll allow me to ask a few questions

How do you access the local frame in Python?

In Python, how do reified stack frames work in relationship to closures?

Do you think reified stack frames are worth it? I thought that combined with prototypal inheritance, there could be some conceptual elegance, at least from a semantic viewpoint. For closures, the current stack frame inherits from the stack frame the closure was created in, which eventually inherits from the global object. Local variable lookups are just object property lookups. There's some elegant consistency in there.

BUT, I'm also thinking, allowing people to read/write/navigate stack frames kind of opens a pandora's box in terms of all the crazy monkey-patching it might allow people to do. Also seems like maybe it isn't really worth it. To implement a debugger in zeta, what we need is some mechanism to read/write locals, but that doesn't necessarily have to be objects. Maybe it isn't really more elegant to try to make stack frames into objects.

I'd like your opinion. Run with this crazy idea and see what happens, or avoid it out of fear of possible consequences for performance and code clarity?

**Comment by whizzter** [comment]
If nothing else i'd say design around stack frames as objects as of no other reason than to keep the implementation clean for continuations.Omitting continuations in a new language today would be on the level of the Java guys skimping on it in 1993, they are a really elegant solution to many async and state spawning problems

**Comment by whizzter** [comment]
If nothing else i'd say design around stack frames as objects as of no other reason than to keep the implementation clean for continuations.Omitting continuations in a new language today would be on the level of the Java guys skimping on it in 1993, they are a really elegant solution to many async and state spawning problems

**Comment by whizzter** [comment]
If nothing else i'd say design around stack frames as objects as of no other reason than to keep the implementation clean and fast for continuations.

Omitting continuations in a new language today would be on the level of the Java guys skimping on closures in 1994, they are a really elegant solution to many async and state spawning problems and when i was writing code for node.js i really lacked them and the ES6 generators are a poor mans option to fix it even if a lot of people are raving about them. (Yet even MS is pushing an "async" variant for c++17).

Stack frames with lazy reification from day one might pay big dividends in that department and could possibly also help with IDE,etc support since people would have an easier time implementing something on top of this.

Now as to optimizations and "user" access. Some variants could be:
* Make the user facing objects read-only and hide temporaries, stuff like templating doesn't need more and debugging is mostly about finding the errors (perhaps different if your language works with images rather than source)
* Read-Write but fixed set of properties depending on the source code rather than runtime manipulations, like sealed JS objects
* Gone wild

Perhaps start at the top and if there's really uses allow more? You could also hide more extensive access for debuggers and specific tools by providing those with specific unstable accessor objects at startup time like sun.misc.Unsafe in Java (although there was a couple of interesting of talks at Java language summit recently on them being somewhat tied down to sun.misc.Unsafe's semantics thanks to people using them for all kinds of things over the years)

Sidenote, I think most demosceners actually write pretty regular code apart from when we're optimizing for tiny intros (4-8k categories and smaller) or optimize for old platforms with self modifying code (c64,early amiga,etc since killing internal code caches has been bad since atleast the pentium(pro?) on x86 and later Amigas also).

**Comment by maximecb** [comment]
I'm still somewhat torn.

Stack frame object pros:
- Semantic consistency: no difference between global scope, module scopes, and stack frames
- Semantic consistency: constant locals are just constant properties of the local frame object
- Semantic consistency: variable lookups, closure variables, global lookups are all just property lookups
- Interpreter implementation is simpler
- Debugger implementation is simpler
- Simpler design for the REPL (shell). The scope the REPL expressions evaluate in can be saved. 
- Possibility of simplifying other things such as exceptions, continuations, coroutines, but this is not entirely clear.

Cons:
- Exposing frames as objects could allow bad/ugly coding practices
- Can make some optimizations difficult or even impossible. If someone captures local variables in a closure, then we have to perform extra work
- The dynamism of stack frame objects must be restricted, we likely can't allow adding new variables or deleting them
- Unclear if this makes inlining easier or more difficult. Inlined functions have stack frames of their own, which we should also keep track of

I think that reified continuations, possibly coroutines, could be implemented as a form of syntactic sugar or other language extension, and do not really need stack frame objects. Anyways. Maybe I'm overthinking this. In the end it's kind of a matter of picking one and going with it. If I put the effort in, I can probably make this fast.

**Comment by cfbolz** [comment]
Agree with your analysis. It's possible to make them fast, but it takes quite some effort.

I like having them in Python. Here's how you get a frame: https://docs.python.org/2/library/sys.html#sys._getframe This is what you can do with them: https://docs.python.org/2/reference/datamodel.html (search for frame). But even in Python they are abused sometimes and lead to really weird code. What's your precise question about the relationship with closures?

If you want to add them I agree with @whizzter that you should very carefully design the API the frame object exposes. They should not expose too much, in order to make optimization not even harder, and to not tie you to an implementation approach too much.

About such design issues there is this paper: http://bracha.org/mirrors.pdf

**Comment by maximecb** [comment]
Thank you very much for your responses @cfbolz. I'll go with it for now. I'm at the point where the whole thing is interpreted anyways. The first JIT I design for this will have very little in the way of optimizations.

API wise, I'll probably make the stack frames read-only for now. I'll try to make the stack layout map to a proper object layout, as if the object was allocated on the stack.

**Comment by maximecb** [comment]
For now, I will not implement stack frame objects, as I want to keep things simple. I might add them in later if it makes sense to do so.
