### ISSUE TITLE
How are arrays and dictionaries supposed to work?

### ISSUE THREAD

**Issue by iankronquist** [maximecb/zeta#16]
I don't see any examples in the readme or in parser.zeta. Presumably like Javascript?

Will riemann have a built in dictionary type? People gripe about how Javascript doesn't have such a type sometimes.

Also, I threw this together last night to practice using a haskell parsing library:
https://github.com/iankronquist/riemann

**Comment by maximecb** [comment]
The arrays will be JS-like, but there will be no "holes". No deletion of elements in the middle of arrays. I added a bit more content to the README doc.

I think that dictionary types should be implemented as one of our officially sanctioned language extensions... Again so that the core language is kept very simple and minimal. The ultimate goal though is that the extensions should really feel native as much as possible.

Riemann, I like your choice of name ;)
