### ISSUE TITLE
Truthiness & falsiness semantics

### ISSUE THREAD

**Issue by maximecb** [maximecb/zeta#8]
There's a question of how if statements should behave. That is, do we want to accept any input type, or only boolean values?

Should ```if a then b``` be acceptable, or only ```if a > 0 then b```

If we accept the former, which values evaluate to true? Nonzero integers? Strings that are not the empty string? Accepting only true and false booleans force people to spell out exactly what is being evaluated, which makes for clearer code, but it also forces things to be slightly more verbose.

**Comment by yawnt** [comment]
i think, since it's dynamically typed, it should just define falsy values (eg: nil, 0, false) and accept those, not just booleans

**Comment by maximecb** [comment]
Glad to see you here yawnt. 

I'll implement it the way you suggested for now :)

**Comment by SBSTP** [comment]
Follow-up question, will there be null pointers or will you use [option types](https://en.wikipedia.org/wiki/Option_type)?

**Comment by maximecb** [comment]
I don't plan on having a null value per-se. I was thinking people can always use the boolean false if they want to represent a null value. Option types, I'm not sure if that fits in the design I have in mind so far, but we will have pattern matching.

**Comment by mollymorphic** [comment]
My personal vote would be for strictness in if-expressions - it should be a Boolean T/F value (or maybe an Option)

One of the benefits of Zeta is that it is an extremely extensible language. I would like to see constructs with complex (or computationally expensive) semantics pushed out of the interpreter/core language and into libraries (whether shipped with Zeta or just imported by the user).

If we create the core if-expression to be very permissive, we can never put that genie back in the bottle. 
An if-expression with more permissible semantics can be constructed on top of a stricter version relatively easily. You just take the input, put it through the desired "truthiness" algorithm, and in then kick it back to native if-expressions.

It's also fairly easy (and more desirable imo than leaving it implicit) to coerce to a Boolean at the points in your code that you need one. Ideally the types we create should have something like .toBoolean() to easily coerce to a Boolean value.

You can construct a stricter version on top of a more permissive one of course - perform an explicit type check on input - but now you're paying runtime penalty for strictness which is more counterintuitive and less desirable than paying a runtime cost for permissiveness IMO.

In terms of implementation, I think for sure all we should say here is something like:
 
    in an if-expression the .toBoolean() method of the value is called, and if the result is true...

Coming up with some general algorithm for "truthiness" as in some language specs is a mistake IMO. For one, it means we have to figure that all out now. We have to think about all the types we want to implement in Zeta, or be able to kludge in others later on. It also is less clean in terms of implementation. We don't want information about types spread all over the codebase. You should be able to learn a lot about a given type just be reading it's .c (or whatever) file(s) - including things like what values are considered true/false for that type.

A bit of a tangent, but I would really like to see first-class support for ADTs in Zeta. They can be implemented as a library, but I think first class support is better, especially if we make them performant. At the very least, we should be considering them and making sure we're not designing a language that is hostile to them.

The fact that this makes code more verbose is a good point. One of the intended uses for Zeta is live-coding and having to type `.toBoolean()` a bunch in your code is not conducive to that...
However, I would say it's quite likely people will want one or more "live coding" language extensions anyway. It'd be easy to use parser extensions to create a dialect of Zeta that is fairly pithy. I think we should target this hypothetical dialect for live-coding applications instead of the general language.

I would say we should err on the side of perf/flexibility/elegence in the core language and put all the nice/fun things in libraries/extensions.

**Comment by maximecb** [comment]
I agree that it's better to be initially stricter and I like the idea of having a toBool method if we're going to do boolean coercion, it makes sense. It's also in line with what I wanted to do for operator overloading. Just to be clear though, are you suggesting that the core language calls this toBool method, or only support true or false and that some extension introduce toBool? There are a number of things to consider.

The semantics of the if statement, especially in the runtime, probably should not involve a runtime function call, as that can lead to infinite recursion and such. It's also a little heavier for the system to deal with (in terms of compilation time, not execution speed) if every if statement involves calls, extra checks, etc. Hence, I would propose that the core language has an if statement that only accepts true/false, and anything else throws an exception.

However, if we have some nice "comfy" extensions that redefine things to make use to toBool, it might be annoying for people to have to import all of these extensions at the beginning of their code file, everything they want to use as part of their favorite extended-zeta-dialect. Possibly, we'll want to pre-define some zeta dialects ourself. So, you might be able to import a package and it will install a collection of extensions at once. My expectation is that people will find the core zeta language pretty crude and will almost always want to extend it. People will of course be able to create their own local modules with their own favorite sets of extensions.

Performance is not that much of an issue. Whether the if statement is strict or not will make little or no difference. Whether you give integers some special boolean meaning, or only accept booleans, you still have to check "is this value a boolean?" Once the system is mature, it will be able to eliminate most such checks, and ideally, if we have toBool method calls, these will get inlined when it matters.

ADTs, you should open a separate issue if you want to get into that discussion. It's not clear what you mean by first-class support for ADTs. You would need to illustrate what you have in mind. That being said, the point of zeta is largely to allow extensions to seem first-class. For instance, I really want matrix math and regexps to be implemented as libraries, but to have native syntax and native performance. People should be able to extend the system, possibly extend the JIT, say, to generate fast machine code for matrix operations and regexps.

**Comment by mollymorphic** [comment]
> Hence, I would propose that the core language has an if statement that only accepts true/false, and anything else throws an exception.

This would be my proposal as well. 

I'll open another issue for ADTs sometime, but agree with the general gist of what you're saying.

RE: your other points, we might want to consider "blessing" certain language extensions or just having a system to use extensions project wide so you don't have to import them for every file in your project. One of us should probably open another issue for this.
